/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => SamplePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var SamplePlugin = class extends import_obsidian.Plugin {
  async onload() {
    console.log("Cargando mi plugin de ejemplo.");
    return Promise.resolve();
  }
  async onunload() {
    console.log("Descargando mi plugin de ejemplo.");
    return Promise.resolve();
  }
};
//# sourceMappingURL=data:application/json;base64,ewogICJ2ZXJzaW9uIjogMywKICAic291cmNlcyI6IFsic3JjL21haW4udHMiXSwKICAic291cmNlc0NvbnRlbnQiOiBbIiAgaW1wb3J0IHsgUGx1Z2luIH0gZnJvbSAnb2JzaWRpYW4nO1xuXG4gIGV4cG9ydCBkZWZhdWx0IGNsYXNzIFNhbXBsZVBsdWdpbiBleHRlbmRzIFBsdWdpbiB7XG4gICAgICBhc3luYyBvbmxvYWQoKSB7XG4gICAgICAgIC8vIENcdTAwRjNkaWdvIGRlIGluaWNpYWxpemFjaVx1MDBGM24gYXF1XHUwMEVEXG5cdCAgICBjb25zb2xlLmxvZygnQ2FyZ2FuZG8gbWkgcGx1Z2luIGRlIGVqZW1wbG8uJyk7XG5cdCAgICByZXR1cm4gUHJvbWlzZS5yZXNvbHZlKCk7XG4gICAgICB9XG5cbiAgICAgIGFzeW5jIG9udW5sb2FkKCkge1xuICAgICAgICAgIC8vIENcdTAwRjNkaWdvIGRlIGxpbXBpZXphIGFxdVx1MDBFRFxuICAgICAgICAgIGNvbnNvbGUubG9nKCdEZXNjYXJnYW5kbyBtaSBwbHVnaW4gZGUgZWplbXBsby4nKTtcbiAgICAgICAgICByZXR1cm4gUHJvbWlzZS5yZXNvbHZlKCk7XG4gICAgICB9XG4gIH1cbiJdLAogICJtYXBwaW5ncyI6ICI7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztBQUFBO0FBQUE7QUFBQTtBQUFBO0FBQUE7QUFBRSxzQkFBdUI7QUFFdkIsSUFBcUIsZUFBckIsY0FBMEMsdUJBQU87QUFBQSxFQUM3QyxNQUFNLFNBQVM7QUFFaEIsWUFBUSxJQUFJLGdDQUFnQztBQUM1QyxXQUFPLFFBQVEsUUFBUTtBQUFBLEVBQ3RCO0FBQUEsRUFFQSxNQUFNLFdBQVc7QUFFYixZQUFRLElBQUksbUNBQW1DO0FBQy9DLFdBQU8sUUFBUSxRQUFRO0FBQUEsRUFDM0I7QUFDSjsiLAogICJuYW1lcyI6IFtdCn0K
